import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import Navbar from "@/components/navbar/navbar";
import LayoutClient from "@/components/layout-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/logo/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
<<<<<<< HEAD
          <LayoutClient>
            {children}
          </LayoutClient>
=======
          <div className="flex">
            <Sidebar />
            <div className="flex-1 ml-[50px]">
              <Navbar />
              <main className="container mx-auto max-w-7xl p-4 sm:p-8 lg:p-12">
                {children}
              </main>
            </div>
          </div>
>>>>>>> e306945224a6eb3b53126efe517d23f7d5d88b5b
          <Toaster
            richColors
            position="top-right"
            toastOptions={{
              classNames: {
                closeButton: "left-auto right-8 top-2",
              },
            }}
            className="z-[9999]"
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
